# Generated by Django 5.0.1 on 2024-02-19 18:51

import enumchoicefield.fields
import storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', enumchoicefield.fields.EnumChoiceField(enum_class=storage.models.Subjects, max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('category', enumchoicefield.fields.EnumChoiceField(enum_class=storage.models.Categories, max_length=8)),
                ('file', models.FileField(upload_to='storage/')),
            ],
        ),
    ]
